version: '3.8'


networks:
  app-net:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - app-net
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - app-net
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  spark:
    image: docker.io/bitnami/spark:2.4.6
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - /tmp:/tmp
    networks:
      - app-net
    ports:
      - '8081:8080'
      - '7077:7077'
  spark-worker:
    image: docker.io/bitnami/spark:2.4.6
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=4
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - /tmp:/tmp
    networks:
      - app-net
  
  bursty:
    image: ghcr.io/bryaneaton/burstytwitterstreams/bursty:latest
    working_dir: /app
    entrypoint: spark-submit --master spark://spark:7077 --executor-memory 1g --conf spark.executor.memoryOverhead=1g --conf spark.driver.maxResultSize=1g --class edu.umd.cs.hcil.twitter.spark.stream.App target/BurstyTwitterStream-2.0-jar-with-dependencies.jar ./conf/streamer.properties ./conf/topics.json log_file.log ./conf/filter_keywords.txt
    networks:
      - app-net

  submit_server:
    image: ghcr.io/bryaneaton/burstytwitterstreams/httpserver:latest
    env_file:
       - ./app/src/main/python/httpServer/main.env
    container_name: submit_server
    networks:
      - app-net
