version: '3.8'


networks:
  app-net:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - app-net
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - app-net
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  spark:
    image: docker.io/bitnami/spark:2.4.6
    container_name: master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - app-net
    ports:
      - '8081:8080'
      - '7077:7077'
  spark-worker-1:
    image: docker.io/bitnami/spark:2.4.6
    container_name: worker1
    ports:
      - '8082:8081'
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=10G
      - SPARK_WORKER_CORES=10
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - app-net
  spark-worker-2:
    image: docker.io/bitnami/spark:2.4.6
    container_name: worker2
    ports:
      - '8083:8081'
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=10G
      - SPARK_WORKER_CORES=10
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - app-net
  bursty:
    image: burstytwitterstreams:latest
    working_dir: /app
    entrypoint: spark-submit --master spark://spark:7077 --executor-memory 10g --conf spark.executor.memoryOverhead=16g --conf spark.driver.maxResultSize=16g --class edu.umd.cs.hcil.twitter.spark.stream.App target/BurstyTwitterStream-2.0-jar-with-dependencies.jar ./conf/streamer.properties ./conf/topics.json log_file.log ./conf/filter_keywords.txt
    networks:
      - app-net

  submit_server:
    image: ./app/src/main/python/httpServer
    env_file:
       - ./app/src/main/python/httpServer/main.env
    container_name: submit_server
    networks:
      - app-net
